version: "3.3"

services:
  web-client:
    build:
      context: ./web/client
      dockerfile: Dockerfile
    ports:
      - "8181:8181"
  server:
    build:
      context: ./web/server
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
  mobile-client:
    build:
      context: ./app
      dockerfile: Dockerfile